/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.demo.controller;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller
public class RegisterController {
      
    @RequestMapping(value="/register",method=RequestMethod.GET)
    public String login(){
        return "registratrion";
    }   
    @Autowired // This means to get the bean called userRepository
           // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/register") // Map ONLY POST Requests
    public String addNewUser (@RequestParam String name
        , @RequestParam String email,  @RequestParam String password, @RequestParam String lastname, @RequestParam String username,RedirectAttributes redirectAttrs) {
      // @ResponseBody means the returned String is the response, not a view name
      // @RequestParam means it is a parameter from the GET or POST request

      User n = new User();
      n.setLastname(lastname);
      n.setUsername(username);
      n.setName(name);
      n.setEmail(email);
      n.setPassword(BCrypt.hashpw(password, BCrypt.gensalt(12)));
      userRepository.save(n);
      redirectAttrs.addFlashAttribute("message", "Register success!!!");
      redirectAttrs.addFlashAttribute("alertClass", "alert-success");
      return "redirect:login";
    }
}
